apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: week5-5
data:
  app-config: |
    key1: value1
    key2: value2
---
apiVersion: v1
kind: Pod
metadata:
  name: config
  namespace: week5-5
spec:
  containers:
    - name: config
      image: redis
      env:
        - name: APP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app-config
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config
