apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsync-data
  namespace: week5-5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-rsync
  namespace: week5-5
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job-rsync
          image: google/cloud-sdk:275.0.0-alpine
          command:
            - gsutil
            - rsync
            - -r
            - gs://my-gcs-bucket/data
            - /data
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rsync-data
