apiVersion: v1
kind: Pod
metadata:
  name: livenessprob
spec:
  containers:
    - name: livenessprob
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
