apiVersion: v1
kind: Pod
metadata:
  name: readinessprob
  namespace: week5-5
spec:
  containers:
    - name: readinessprob
      image: gcr.io/k8s-k3s/demo:v2.0.0
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
