apiVersion: v1
kind: Pod
metadata:
  name: resource
  namespace: week5-5
spec:
  containers:
    - name: resource
      image: gcr.io/kuar-demo/kuard-amd64:1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
