apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
stringData:
  username: admin
  password: s3cr3t
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - name: secret-env
      image: redis
      env:
        - name: MY_SECRET_USER
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: username
        - name: MY_SECRET_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password
