apiVersion: v1
kind: Pod
metadata:
  name: volume
  namespace: week5-5
spec:
  containers:
    - name: volume
      image: gcr.io/kuar-demo/kuard-amd64:1
      volumeMounts:
        - name: host-data
          mountPath: /data
  volumes:
    - name: host-data
      hostPath:
        path: /var/lib/kuard
        type: Directory
